CREATE OR REPLACE TRIGGER HR.TRG_EMPLOYE_ID_INS
  BEFORE INSERT ON HR.EMPLOYEE
  FOR EACH ROW

DECLARE
  V_EMPLOYEE_ID HR.EMPLOYEE.EMPLOYEE_ID%TYPE;
BEGIN
 V_EMPLOYEE_ID := HR.EMPLOYEE_SEQ.NEXTVAL;

  IF V_EMPLOYEE_ID IS NOT NULL AND :NEW.EMPLOYEE_ID IS NULL THEN
    :NEW.EMPLOYEE_ID := V_EMPLOYEE_ID;
  END IF;

EXCEPTION
  WHEN OTHERS THEN
    RAISE_APPLICATION_ERROR(-20007, SQLERRM);
END;
/
